package com.example.demo;// Generated by Selenium IDE
import org.junit.Test;


import org.openqa.selenium.*;

public class InsertarAlumnoTest extends SeleniumConfig{


  @Test
  public void insertarAlumno() throws InterruptedException {

    this.driver.get("http://157.245.12.218:80/");

    //this.driver.navigate().to("http://localhost:8080/");

    this.driver.manage().window().setSize(new Dimension(1036, 828));

    WebElement name = this.driver.findElement(By.id("input-23"));
    name.sendKeys("SeleniumTest");
    WebElement rut = this.driver.findElement(By.id("input-27"));
    rut.sendKeys("1.111.111-1");
    WebElement dateWidget = this.driver.findElement(By.id("input-32"));
    dateWidget.click();


    WebElement day = this.driver.findElement(By.xpath("//*[@id=\"app\"]/div[1]/div/div/div[2]/div/div[2]/table/tbody/tr[3]/td[3]/button"));
    day.click();
    Thread.sleep(1000);
    this.driver.findElement(By.id("button_ok")).click();

    Thread.sleep(1000);
    WebElement dropDown = this.driver.findElement(By.cssSelector(".v-select__selections"));
    dropDown.click();

    Thread.sleep(1000);
    this.driver.findElement(By.xpath("//*[@id=\"ingeniería-civil-en-electricidad-list-item-67\"]")).click();

    this.driver.findElement(By.cssSelector(".v-input--selection-controls__ripple")).click();
    this.driver.findElement(By.cssSelector(".success > .v-btn__content")).click();



    }
}
